<template>
  <div>
    <AdminPageHeader title="Mises à jour" description="Veille PaperMC et plugins officiels. Le moniteur signale et documente, mais n’installe jamais automatiquement.">
      <button v-if="canCheck" class="rounded-xl bg-orange-500 px-4 py-2 text-sm font-black text-zinc-950 disabled:opacity-50" :disabled="checking" @click="check">{{ checking ? "Vérification…" : "Vérifier maintenant" }}</button>
    </AdminPageHeader>
    <AdminNotice v-if="notice" :tone="noticeTone" class="mb-6">{{ notice }}</AdminNotice>
    <section class="grid gap-4 md:grid-cols-3"><article class="rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><p class="text-sm text-zinc-400">Sources accessibles</p><p class="mt-2 text-2xl font-black">{{ lastRun?.successfulSources ?? "—" }}/{{ lastRun?.totalSources ?? "—" }}</p></article><article class="rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><p class="text-sm text-zinc-400">Dernière vérification</p><p class="mt-2 text-lg font-black">{{ formatDate(lastRun?.checkedAt || status?.lastSuccessfulRunAt) }}</p></article><article class="rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><p class="text-sm text-zinc-400">Mises à jour détectées</p><p class="mt-2 text-2xl font-black text-orange-300">{{ availableUpdates.length }}</p></article></section>
    <section v-if="lastRun?.results?.length" class="mt-6 overflow-x-auto rounded-2xl border border-zinc-800 bg-zinc-900"><table class="w-full min-w-[760px] text-left text-sm"><thead class="border-b border-zinc-800 text-xs uppercase text-zinc-500"><tr><th class="p-4">Composant</th><th class="p-4">Installé</th><th class="p-4">Stable</th><th class="p-4">État</th><th class="p-4">Changelog</th></tr></thead><tbody><tr v-for="component in lastRun.results" :key="component.id" class="border-b border-zinc-800/70 last:border-0"><td class="p-4 font-bold">{{ component.name }}</td><td class="p-4 font-mono"><span class="block">{{ component.installed || "inconnu" }}</span><span v-if="component.installedSource === 'runtime-snapshot'" class="mt-1 block font-sans text-xs text-zinc-500" :title="component.installedWarning || component.installedObservedAt">{{ component.installedWarning ? "runtime non vérifié" : "runtime vérifié" }}</span></td><td class="p-4 font-mono">{{ component.target || "—" }}</td><td class="p-4" :class="component.status === 'update-available' ? 'text-orange-300' : component.status === 'current' || component.status === 'installed-newer' ? 'text-emerald-300' : 'text-red-300'">{{ component.status }}</td><td class="p-4"><a v-if="component.changelogUrl" :href="component.changelogUrl" target="_blank" rel="noopener noreferrer" class="text-orange-300 hover:underline">Ouvrir</a></td></tr></tbody></table></section>
    <section class="mt-8 grid gap-6 xl:grid-cols-2">
      <article class="min-w-0 rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><div class="mb-4 flex items-center gap-3"><h2 class="mr-auto text-xl font-black">Rapport</h2><button class="rounded-lg border border-zinc-700 px-3 py-2 text-sm" @click="copy(report, 'Rapport')">Copier</button></div><pre class="max-h-[680px] overflow-auto whitespace-pre-wrap rounded-xl bg-black p-4 text-xs leading-6 text-zinc-300">{{ report || "Aucun rapport disponible." }}</pre></article>
      <article class="min-w-0 rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><div class="mb-4 flex items-center gap-3"><h2 class="mr-auto text-xl font-black">Prompt pour une IA</h2><button class="rounded-lg border border-zinc-700 px-3 py-2 text-sm" @click="copy(prompt, 'Prompt')">Copier</button></div><pre class="max-h-[680px] overflow-auto whitespace-pre-wrap rounded-xl bg-black p-4 text-xs leading-6 text-zinc-300">{{ prompt || "Aucun prompt disponible." }}</pre></article>
    </section>
  </div>
</template>

<script setup lang="ts">
definePageMeta({ layout: "admin", middleware: "admin" });
useSeoMeta({ title: "Mises à jour admin | Cookie Build", robots: "noindex, nofollow" });
const canCheck = useAdminAccess("updates:write"); const status = ref<Record<string, any> | null>(null); const report = ref(""); const prompt = ref(""); const checking = ref(false); const notice = ref(""); const noticeTone = ref<"error" | "success">("success");
const lastRun = computed(() => status.value?.lastRun || null); const availableUpdates = computed(() => (lastRun.value?.results || []).filter((item: any) => item.updateAvailable));
async function load() { const results = await Promise.allSettled([adminRequest<{ data: Record<string, any> }>("/api/admin/updates/status"), adminRequest<{ data: { content: string } }>("/api/admin/updates/report"), adminRequest<{ data: { content: string } }>("/api/admin/updates/prompt")]); if (results[0].status === "fulfilled") status.value = results[0].value.data; if (results[1].status === "fulfilled") report.value = results[1].value.data.content; if (results[2].status === "fulfilled") prompt.value = results[2].value.data.content; if (results.every((result) => result.status === "rejected")) { notice.value = "Le moniteur de mises à jour est indisponible."; noticeTone.value = "error"; } }
async function check() { checking.value = true; notice.value = ""; try { await adminRequest("/api/admin/updates/check", { method: "POST", body: {} }); notice.value = "Vérification terminée. Rapport et prompt actualisés."; noticeTone.value = "success"; await load(); } catch (error) { notice.value = adminErrorMessage(error); noticeTone.value = "error"; } finally { checking.value = false; } }
async function copy(value: string, label: string) { try { await navigator.clipboard.writeText(value); notice.value = `${label} copié.`; noticeTone.value = "success"; } catch { notice.value = "Copie impossible."; noticeTone.value = "error"; } }
function formatDate(value?: string) { return value ? new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—"; }
await load();
</script>
