import type { BuildGalleryTab, BuildReportReason } from "./build-gallery";
import type { SiteLocaleCode } from "./site-locales";

export interface BuildGalleryCopy {
  seoTitle: string;
  seoDescription: string;
  eyebrow: string;
  title: string;
  intro: string;
  tabsLabel: string;
  tabs: Record<BuildGalleryTab, string>;
  loadMore: string;
  loading: string;
  empty: string;
  emptyCta: string;
  error: string;
  retry: string;
  likes: (count: number, formatted: string) => string;
  by: (player: string) => string;
  cardAlt: (theme: string, player: string) => string;
  placement: (place: number) => string;
  solo: string;
  detail: {
    seoTitle: (theme: string, player: string) => string;
    seoDescription: (theme: string, player: string) => string;
    back: string;
    theme: string;
    builtOn: (date: string) => string;
    blocks: (formatted: string) => string;
    like: string;
    unlike: string;
    likeError: string;
    share: string;
    shareTitle: (theme: string, player: string) => string;
    shareText: (theme: string, player: string) => string;
    copyLink: string;
    link: string;
    shareOnX: string;
    shareOnWhatsApp: string;
    openImage: string;
    report: string;
    reportTitle: string;
    reportIntro: string;
    reasons: Record<BuildReportReason, string>;
    reportSubmit: string;
    reportCancel: string;
    reportThanks: string;
    reportError: string;
    moreFrom: (player: string) => string;
    seeAllFrom: (player: string) => string;
    ctaTitle: string;
    ctaBody: string;
    ctaButton: string;
    ctaJoin: string;
    unavailable: string;
  };
  viewer: {
    label: (theme: string, player: string) => string;
    loading: string;
    error: string;
    webglFallback: string;
    reset: string;
    screenshot: string;
    fullscreen: string;
    exitFullscreen: string;
    pause: string;
    play: string;
    keyboardHelp: string;
    open3d: string;
  };
  home: {
    title: string;
    intro: string;
    all: string;
  };
  landing: {
    title: string;
    body: string;
    cta: string;
  };
}

export const BUILD_GALLERY_COPY: Record<SiteLocaleCode, BuildGalleryCopy> = {
  en: {
    seoTitle: "Build Battle Gallery: the best Minecraft builds | Cookie Build",
    seoDescription: "Explore the best Build Battle creations from Cookie Build players in 3D. Best of the week, of the month and of all time, plus the latest builds.",
    eyebrow: "Build Battle",
    title: "Build Battle gallery",
    intro: "Every Build Battle build lands here at the end of the match. Spin them in 3D, like your favourites and share them. Each week, the 3 most-liked builds win coins!",
    tabsLabel: "Sort builds",
    tabs: { week: "Best of the week", month: "Best of the month", all: "All time", recent: "Latest" },
    loadMore: "Load more",
    loading: "Loading builds…",
    empty: "No builds here yet. Play a Build Battle match and yours could be the first!",
    emptyCta: "How to play",
    error: "The gallery could not be loaded right now.",
    retry: "Try again",
    likes: (count, formatted) => `${formatted} ${count === 1 ? "like" : "likes"}`,
    by: (player) => `by ${player}`,
    cardAlt: (theme, player) => `“${theme}” build by ${player} in Build Battle`,
    placement: (place) => (place === 1 ? "Winner" : place === 2 ? "2nd place" : place === 3 ? "3rd place" : `${place}th place`),
    solo: "Solo",
    detail: {
      seoTitle: (theme, player) => `“${theme}” by ${player} – Build Battle | Cookie Build`,
      seoDescription: (theme, player) => `Explore ${player}'s “${theme}” Build Battle build in 3D on Cookie Build, then like it and share it.`,
      back: "All builds",
      theme: "Theme",
      builtOn: (date) => `Built on ${date}`,
      blocks: (formatted) => `${formatted} blocks`,
      like: "Like this build",
      unlike: "Remove your like",
      likeError: "Your like could not be saved. Try again in a moment.",
      share: "Share",
      shareTitle: (theme, player) => `“${theme}” by ${player}`,
      shareText: (theme, player) => `Check out the “${theme}” build by ${player} on Cookie Build!`,
      copyLink: "Copy link",
      link: "Link",
      shareOnX: "Share on X",
      shareOnWhatsApp: "Share on WhatsApp",
      openImage: "Open the image",
      report: "Report",
      reportTitle: "Report this build",
      reportIntro: "Tell us what is wrong. Our team reviews every report.",
      reasons: { offensive: "Offensive or hateful", inappropriate: "Inappropriate content", other: "Something else" },
      reportSubmit: "Send report",
      reportCancel: "Cancel",
      reportThanks: "Thanks, your report has been sent.",
      reportError: "The report could not be sent. Try again later.",
      moreFrom: (player) => `More builds by ${player}`,
      seeAllFrom: (player) => `All builds by ${player}`,
      ctaTitle: "Want your build in the gallery?",
      ctaBody: "Join Build Battle on Cookie Build: you get a theme and a few minutes to build. At the end of the match, your build appears here automatically.",
      ctaButton: "Discover Build Battle",
      ctaJoin: "How to join the server",
      unavailable: "This build could not be loaded right now.",
    },
    viewer: {
      label: (theme, player) => `3D view of “${theme}” by ${player}`,
      loading: "Loading the 3D build…",
      error: "The 3D view could not be loaded.",
      webglFallback: "3D is not available on this device, here is a picture of the build instead.",
      reset: "Reset view",
      screenshot: "Save a screenshot",
      fullscreen: "Full screen",
      exitFullscreen: "Exit full screen",
      pause: "Stop rotation",
      play: "Rotate automatically",
      keyboardHelp: "Drag to rotate, pinch or scroll to zoom. Keyboard: arrow keys rotate, + and − zoom, 0 resets.",
      open3d: "Open in 3D",
    },
    home: { title: "Best builds of the week", intro: "The most-liked Build Battle creations of the week.", all: "Open the gallery" },
    landing: {
      title: "Your builds, in 3D",
      body: "Every build is saved at the end of the match. Explore the best ones in 3D, like them and share yours with friends.",
      cta: "Open the Build Battle gallery",
    },
  },
  fr: {
    seoTitle: "Galerie Build Battle : les meilleures constructions Minecraft | Cookie Build",
    seoDescription: "Découvre en 3D les meilleures constructions Build Battle des joueurs de Cookie Build : best of de la semaine, du mois, de tous les temps et les dernières créations.",
    eyebrow: "Build Battle",
    title: "Galerie Build Battle",
    intro: "Chaque construction Build Battle arrive ici à la fin de la partie. Fais-les tourner en 3D, like tes préférées et partage-les. Chaque semaine, les 3 constructions les plus likées gagnent des pièces !",
    tabsLabel: "Trier les constructions",
    tabs: { week: "Best of semaine", month: "Best of du mois", all: "Tout temps", recent: "Récentes" },
    loadMore: "Voir plus",
    loading: "Chargement des constructions…",
    empty: "Aucune construction ici pour l'instant. Joue une partie de Build Battle et la tienne sera peut-être la première !",
    emptyCta: "Comment jouer",
    error: "Impossible de charger la galerie pour le moment.",
    retry: "Réessayer",
    likes: (_count, formatted) => `${formatted} j'aime`,
    by: (player) => `par ${player}`,
    cardAlt: (theme, player) => `Construction « ${theme} » de ${player} en Build Battle`,
    placement: (place) => (place === 1 ? "Gagnant" : `${place}e place`),
    solo: "Solo",
    detail: {
      seoTitle: (theme, player) => `« ${theme} » par ${player} – Build Battle | Cookie Build`,
      seoDescription: (theme, player) => `Explore en 3D la construction « ${theme} » de ${player} en Build Battle sur Cookie Build, puis like-la et partage-la.`,
      back: "Toutes les constructions",
      theme: "Thème",
      builtOn: (date) => `Construite le ${date}`,
      blocks: (formatted) => `${formatted} blocs`,
      like: "J'aime cette construction",
      unlike: "Retirer ton j'aime",
      likeError: "Ton j'aime n'a pas pu être enregistré. Réessaie dans un instant.",
      share: "Partager",
      shareTitle: (theme, player) => `« ${theme} » par ${player}`,
      shareText: (theme, player) => `Regarde la construction « ${theme} » de ${player} sur Cookie Build !`,
      copyLink: "Copier le lien",
      link: "Lien",
      shareOnX: "Partager sur X",
      shareOnWhatsApp: "Partager sur WhatsApp",
      openImage: "Ouvrir l'image",
      report: "Signaler",
      reportTitle: "Signaler cette construction",
      reportIntro: "Dis-nous ce qui ne va pas. Notre équipe examine chaque signalement.",
      reasons: { offensive: "Offensante ou haineuse", inappropriate: "Contenu inapproprié", other: "Autre chose" },
      reportSubmit: "Envoyer le signalement",
      reportCancel: "Annuler",
      reportThanks: "Merci, ton signalement a bien été envoyé.",
      reportError: "Le signalement n'a pas pu être envoyé. Réessaie plus tard.",
      moreFrom: (player) => `Autres constructions de ${player}`,
      seeAllFrom: (player) => `Toutes les constructions de ${player}`,
      ctaTitle: "Envie de voir ta construction ici ?",
      ctaBody: "Rejoins le Build Battle sur Cookie Build : tu reçois un thème et quelques minutes pour construire. À la fin de la partie, ta construction apparaît ici automatiquement.",
      ctaButton: "Découvrir le Build Battle",
      ctaJoin: "Comment rejoindre le serveur",
      unavailable: "Impossible de charger cette construction pour le moment.",
    },
    viewer: {
      label: (theme, player) => `Vue 3D de « ${theme} » par ${player}`,
      loading: "Chargement de la construction en 3D…",
      error: "Impossible d'afficher la vue 3D.",
      webglFallback: "La 3D n'est pas disponible sur cet appareil, voici une image de la construction.",
      reset: "Réinitialiser la vue",
      screenshot: "Enregistrer une capture",
      fullscreen: "Plein écran",
      exitFullscreen: "Quitter le plein écran",
      pause: "Arrêter la rotation",
      play: "Rotation automatique",
      keyboardHelp: "Fais glisser pour tourner, pince ou fais défiler pour zoomer. Clavier : flèches pour tourner, + et − pour zoomer, 0 pour réinitialiser.",
      open3d: "Voir en 3D",
    },
    home: { title: "Best of de la semaine", intro: "Les constructions Build Battle les plus likées de la semaine.", all: "Voir la galerie" },
    landing: {
      title: "Tes constructions en 3D",
      body: "Chaque construction est sauvegardée à la fin de la partie. Explore les meilleures en 3D, like-les et partage les tiennes avec tes amis.",
      cta: "Ouvrir la galerie Build Battle",
    },
  },
  de: {
    seoTitle: "Build-Battle-Galerie: die besten Minecraft-Bauwerke | Cookie Build",
    seoDescription: "Entdecke die besten Build-Battle-Bauwerke der Cookie-Build-Spieler in 3D: Best of der Woche, des Monats, aller Zeiten und die neuesten Bauten.",
    eyebrow: "Build Battle",
    title: "Build-Battle-Galerie",
    intro: "Jedes Build-Battle-Bauwerk landet am Ende der Runde hier. Dreh es in 3D, like deine Favoriten und teile sie. Jede Woche gewinnen die 3 Bauwerke mit den meisten Likes Münzen!",
    tabsLabel: "Bauwerke sortieren",
    tabs: { week: "Best of der Woche", month: "Best of des Monats", all: "Aller Zeiten", recent: "Neueste" },
    loadMore: "Mehr laden",
    loading: "Bauwerke werden geladen…",
    empty: "Hier gibt es noch keine Bauwerke. Spiel eine Runde Build Battle – vielleicht ist deins das erste!",
    emptyCta: "So wird gespielt",
    error: "Die Galerie kann gerade nicht geladen werden.",
    retry: "Erneut versuchen",
    likes: (count, formatted) => `${formatted} ${count === 1 ? "Like" : "Likes"}`,
    by: (player) => `von ${player}`,
    cardAlt: (theme, player) => `Bauwerk „${theme}“ von ${player} in Build Battle`,
    placement: (place) => (place === 1 ? "Sieger" : `${place}. Platz`),
    solo: "Solo",
    detail: {
      seoTitle: (theme, player) => `„${theme}“ von ${player} – Build Battle | Cookie Build`,
      seoDescription: (theme, player) => `Entdecke das Build-Battle-Bauwerk „${theme}“ von ${player} in 3D auf Cookie Build, like und teile es.`,
      back: "Alle Bauwerke",
      theme: "Thema",
      builtOn: (date) => `Gebaut am ${date}`,
      blocks: (formatted) => `${formatted} Blöcke`,
      like: "Dieses Bauwerk liken",
      unlike: "Like entfernen",
      likeError: "Dein Like konnte nicht gespeichert werden. Versuch es gleich noch einmal.",
      share: "Teilen",
      shareTitle: (theme, player) => `„${theme}“ von ${player}`,
      shareText: (theme, player) => `Schau dir das Bauwerk „${theme}“ von ${player} auf Cookie Build an!`,
      copyLink: "Link kopieren",
      link: "Link",
      shareOnX: "Auf X teilen",
      shareOnWhatsApp: "Auf WhatsApp teilen",
      openImage: "Bild öffnen",
      report: "Melden",
      reportTitle: "Dieses Bauwerk melden",
      reportIntro: "Sag uns, was nicht stimmt. Unser Team prüft jede Meldung.",
      reasons: { offensive: "Beleidigend oder hasserfüllt", inappropriate: "Unangemessener Inhalt", other: "Etwas anderes" },
      reportSubmit: "Meldung senden",
      reportCancel: "Abbrechen",
      reportThanks: "Danke, deine Meldung wurde gesendet.",
      reportError: "Die Meldung konnte nicht gesendet werden. Versuch es später erneut.",
      moreFrom: (player) => `Weitere Bauwerke von ${player}`,
      seeAllFrom: (player) => `Alle Bauwerke von ${player}`,
      ctaTitle: "Willst du dein Bauwerk hier sehen?",
      ctaBody: "Spiel Build Battle auf Cookie Build: Du bekommst ein Thema und ein paar Minuten Bauzeit. Am Ende der Runde erscheint dein Bauwerk automatisch hier.",
      ctaButton: "Build Battle entdecken",
      ctaJoin: "So trittst du dem Server bei",
      unavailable: "Dieses Bauwerk kann gerade nicht geladen werden.",
    },
    viewer: {
      label: (theme, player) => `3D-Ansicht von „${theme}“ von ${player}`,
      loading: "3D-Bauwerk wird geladen…",
      error: "Die 3D-Ansicht konnte nicht geladen werden.",
      webglFallback: "3D ist auf diesem Gerät nicht verfügbar – hier ist stattdessen ein Bild des Bauwerks.",
      reset: "Ansicht zurücksetzen",
      screenshot: "Screenshot speichern",
      fullscreen: "Vollbild",
      exitFullscreen: "Vollbild beenden",
      pause: "Drehung stoppen",
      play: "Automatisch drehen",
      keyboardHelp: "Ziehen zum Drehen, Zwei-Finger-Geste oder Mausrad zum Zoomen. Tastatur: Pfeiltasten drehen, + und − zoomen, 0 setzt zurück.",
      open3d: "In 3D ansehen",
    },
    home: { title: "Best of der Woche", intro: "Die Build-Battle-Bauwerke mit den meisten Likes dieser Woche.", all: "Zur Galerie" },
    landing: {
      title: "Deine Bauwerke in 3D",
      body: "Jedes Bauwerk wird am Ende der Runde gespeichert. Entdecke die besten in 3D, like sie und teile deine mit Freunden.",
      cta: "Build-Battle-Galerie öffnen",
    },
  },
  it: {
    seoTitle: "Galleria Build Battle: le migliori costruzioni Minecraft | Cookie Build",
    seoDescription: "Scopri in 3D le migliori costruzioni Build Battle dei giocatori di Cookie Build: best of della settimana, del mese, di sempre e le ultime creazioni.",
    eyebrow: "Build Battle",
    title: "Galleria Build Battle",
    intro: "Ogni costruzione di Build Battle arriva qui a fine partita. Falla ruotare in 3D, metti mi piace alle tue preferite e condividile. Ogni settimana le 3 costruzioni con più mi piace vincono monete!",
    tabsLabel: "Ordina le costruzioni",
    tabs: { week: "Best of della settimana", month: "Best of del mese", all: "Di sempre", recent: "Più recenti" },
    loadMore: "Carica altre",
    loading: "Caricamento delle costruzioni…",
    empty: "Ancora nessuna costruzione qui. Gioca una partita di Build Battle: la tua potrebbe essere la prima!",
    emptyCta: "Come si gioca",
    error: "Al momento non è possibile caricare la galleria.",
    retry: "Riprova",
    likes: (_count, formatted) => `${formatted} mi piace`,
    by: (player) => `di ${player}`,
    cardAlt: (theme, player) => `Costruzione «${theme}» di ${player} in Build Battle`,
    placement: (place) => (place === 1 ? "Vincitore" : `${place}º posto`),
    solo: "Solo",
    detail: {
      seoTitle: (theme, player) => `«${theme}» di ${player} – Build Battle | Cookie Build`,
      seoDescription: (theme, player) => `Esplora in 3D la costruzione «${theme}» di ${player} in Build Battle su Cookie Build, poi metti mi piace e condividila.`,
      back: "Tutte le costruzioni",
      theme: "Tema",
      builtOn: (date) => `Costruita il ${date}`,
      blocks: (formatted) => `${formatted} blocchi`,
      like: "Mi piace questa costruzione",
      unlike: "Togli il tuo mi piace",
      likeError: "Non è stato possibile salvare il tuo mi piace. Riprova tra poco.",
      share: "Condividi",
      shareTitle: (theme, player) => `«${theme}» di ${player}`,
      shareText: (theme, player) => `Guarda la costruzione «${theme}» di ${player} su Cookie Build!`,
      copyLink: "Copia link",
      link: "Link",
      shareOnX: "Condividi su X",
      shareOnWhatsApp: "Condividi su WhatsApp",
      openImage: "Apri l'immagine",
      report: "Segnala",
      reportTitle: "Segnala questa costruzione",
      reportIntro: "Dicci cosa non va. Il nostro team esamina ogni segnalazione.",
      reasons: { offensive: "Offensiva o d'odio", inappropriate: "Contenuto inappropriato", other: "Altro" },
      reportSubmit: "Invia segnalazione",
      reportCancel: "Annulla",
      reportThanks: "Grazie, la tua segnalazione è stata inviata.",
      reportError: "Non è stato possibile inviare la segnalazione. Riprova più tardi.",
      moreFrom: (player) => `Altre costruzioni di ${player}`,
      seeAllFrom: (player) => `Tutte le costruzioni di ${player}`,
      ctaTitle: "Vuoi vedere la tua costruzione qui?",
      ctaBody: "Gioca a Build Battle su Cookie Build: ricevi un tema e qualche minuto per costruire. A fine partita la tua costruzione appare qui automaticamente.",
      ctaButton: "Scopri Build Battle",
      ctaJoin: "Come entrare nel server",
      unavailable: "Al momento non è possibile caricare questa costruzione.",
    },
    viewer: {
      label: (theme, player) => `Vista 3D di «${theme}» di ${player}`,
      loading: "Caricamento della costruzione in 3D…",
      error: "Impossibile caricare la vista 3D.",
      webglFallback: "Il 3D non è disponibile su questo dispositivo: ecco un'immagine della costruzione.",
      reset: "Reimposta la vista",
      screenshot: "Salva uno screenshot",
      fullscreen: "Schermo intero",
      exitFullscreen: "Esci da schermo intero",
      pause: "Ferma la rotazione",
      play: "Rotazione automatica",
      keyboardHelp: "Trascina per ruotare, pizzica o scorri per lo zoom. Tastiera: frecce per ruotare, + e − per lo zoom, 0 per reimpostare.",
      open3d: "Guarda in 3D",
    },
    home: { title: "Best of della settimana", intro: "Le costruzioni Build Battle con più mi piace della settimana.", all: "Apri la galleria" },
    landing: {
      title: "Le tue costruzioni in 3D",
      body: "Ogni costruzione viene salvata a fine partita. Esplora le migliori in 3D, metti mi piace e condividi le tue con gli amici.",
      cta: "Apri la galleria Build Battle",
    },
  },
  bg: {
    seoTitle: "Галерия Build Battle: най-добрите Minecraft постройки | Cookie Build",
    seoDescription: "Разгледай в 3D най-добрите Build Battle постройки на играчите в Cookie Build: най-доброто за седмицата, месеца, за всички времена и най-новите творби.",
    eyebrow: "Build Battle",
    title: "Галерия Build Battle",
    intro: "Всяка постройка от Build Battle идва тук в края на мача. Завъртай ги в 3D, харесвай любимите си и ги споделяй. Всяка седмица трите най-харесвани постройки печелят монети!",
    tabsLabel: "Подреди постройките",
    tabs: { week: "Най-доброто за седмицата", month: "Най-доброто за месеца", all: "За всички времена", recent: "Най-нови" },
    loadMore: "Зареди още",
    loading: "Зареждане на постройките…",
    empty: "Тук още няма постройки. Изиграй мач в Build Battle и твоята може да е първата!",
    emptyCta: "Как се играе",
    error: "Галерията не може да се зареди в момента.",
    retry: "Опитай отново",
    likes: (count, formatted) => `${formatted} ${count === 1 ? "харесване" : "харесвания"}`,
    by: (player) => `от ${player}`,
    cardAlt: (theme, player) => `Постройка „${theme}“ от ${player} в Build Battle`,
    placement: (place) => (place === 1 ? "Победител" : `${place}-о място`),
    solo: "Соло",
    detail: {
      seoTitle: (theme, player) => `„${theme}“ от ${player} – Build Battle | Cookie Build`,
      seoDescription: (theme, player) => `Разгледай в 3D постройката „${theme}“ на ${player} от Build Battle в Cookie Build, харесай я и я сподели.`,
      back: "Всички постройки",
      theme: "Тема",
      builtOn: (date) => `Построена на ${date}`,
      blocks: (formatted) => `${formatted} блока`,
      like: "Харесай тази постройка",
      unlike: "Премахни харесването",
      likeError: "Харесването ти не беше запазено. Опитай отново след малко.",
      share: "Сподели",
      shareTitle: (theme, player) => `„${theme}“ от ${player}`,
      shareText: (theme, player) => `Виж постройката „${theme}“ на ${player} в Cookie Build!`,
      copyLink: "Копирай линка",
      link: "Линкът",
      shareOnX: "Сподели в X",
      shareOnWhatsApp: "Сподели в WhatsApp",
      openImage: "Отвори изображението",
      report: "Докладвай",
      reportTitle: "Докладвай тази постройка",
      reportIntro: "Кажи ни какво не е наред. Екипът ни преглежда всеки доклад.",
      reasons: { offensive: "Обидна или изпълнена с омраза", inappropriate: "Неподходящо съдържание", other: "Друго" },
      reportSubmit: "Изпрати доклада",
      reportCancel: "Отказ",
      reportThanks: "Благодарим, докладът ти е изпратен.",
      reportError: "Докладът не можа да бъде изпратен. Опитай по-късно.",
      moreFrom: (player) => `Още постройки от ${player}`,
      seeAllFrom: (player) => `Всички постройки от ${player}`,
      ctaTitle: "Искаш ли постройката ти да е тук?",
      ctaBody: "Играй Build Battle в Cookie Build: получаваш тема и няколко минути за строене. В края на мача постройката ти се появява тук автоматично.",
      ctaButton: "Открий Build Battle",
      ctaJoin: "Как да влезеш в сървъра",
      unavailable: "Тази постройка не може да се зареди в момента.",
    },
    viewer: {
      label: (theme, player) => `3D изглед на „${theme}“ от ${player}`,
      loading: "Зареждане на 3D постройката…",
      error: "3D изгледът не можа да се зареди.",
      webglFallback: "3D не се поддържа на това устройство, ето снимка на постройката.",
      reset: "Нулирай изгледа",
      screenshot: "Запази екранна снимка",
      fullscreen: "Цял екран",
      exitFullscreen: "Изход от цял екран",
      pause: "Спри въртенето",
      play: "Автоматично въртене",
      keyboardHelp: "Плъзни, за да завъртиш, събери пръсти или скролни за мащаб. Клавиатура: стрелките въртят, + и − мащабират, 0 нулира.",
      open3d: "Виж в 3D",
    },
    home: { title: "Най-доброто за седмицата", intro: "Най-харесваните Build Battle постройки за седмицата.", all: "Към галерията" },
    landing: {
      title: "Твоите постройки в 3D",
      body: "Всяка постройка се запазва в края на мача. Разгледай най-добрите в 3D, харесвай ги и споделяй своите с приятели.",
      cta: "Отвори галерията Build Battle",
    },
  },
  es: {
    seoTitle: "Galería de Build Battle: las mejores construcciones de Minecraft | Cookie Build",
    seoDescription: "Descubre en 3D las mejores construcciones de Build Battle de los jugadores de Cookie Build: lo mejor de la semana, del mes, de todos los tiempos y las más recientes.",
    eyebrow: "Build Battle",
    title: "Galería de Build Battle",
    intro: "Cada construcción de Build Battle llega aquí al final de la partida. Gíralas en 3D, dale me gusta a tus favoritas y compártelas. ¡Cada semana, las 3 construcciones con más me gusta ganan monedas!",
    tabsLabel: "Ordenar construcciones",
    tabs: { week: "Lo mejor de la semana", month: "Lo mejor del mes", all: "De todos los tiempos", recent: "Recientes" },
    loadMore: "Cargar más",
    loading: "Cargando construcciones…",
    empty: "Todavía no hay construcciones aquí. ¡Juega una partida de Build Battle y la tuya podría ser la primera!",
    emptyCta: "Cómo jugar",
    error: "No se pudo cargar la galería en este momento.",
    retry: "Reintentar",
    likes: (_count, formatted) => `${formatted} me gusta`,
    by: (player) => `de ${player}`,
    cardAlt: (theme, player) => `Construcción «${theme}» de ${player} en Build Battle`,
    placement: (place) => (place === 1 ? "Ganador" : `${place}.º puesto`),
    solo: "Solo",
    detail: {
      seoTitle: (theme, player) => `«${theme}» de ${player} – Build Battle | Cookie Build`,
      seoDescription: (theme, player) => `Explora en 3D la construcción «${theme}» de ${player} en Build Battle en Cookie Build, dale me gusta y compártela.`,
      back: "Todas las construcciones",
      theme: "Tema",
      builtOn: (date) => `Construida el ${date}`,
      blocks: (formatted) => `${formatted} bloques`,
      like: "Me gusta esta construcción",
      unlike: "Quitar tu me gusta",
      likeError: "No se pudo guardar tu me gusta. Inténtalo de nuevo en un momento.",
      share: "Compartir",
      shareTitle: (theme, player) => `«${theme}» de ${player}`,
      shareText: (theme, player) => `¡Mira la construcción «${theme}» de ${player} en Cookie Build!`,
      copyLink: "Copiar enlace",
      link: "Enlace",
      shareOnX: "Compartir en X",
      shareOnWhatsApp: "Compartir en WhatsApp",
      openImage: "Abrir la imagen",
      report: "Denunciar",
      reportTitle: "Denunciar esta construcción",
      reportIntro: "Cuéntanos qué pasa. Nuestro equipo revisa cada denuncia.",
      reasons: { offensive: "Ofensiva o de odio", inappropriate: "Contenido inapropiado", other: "Otro motivo" },
      reportSubmit: "Enviar denuncia",
      reportCancel: "Cancelar",
      reportThanks: "Gracias, tu denuncia se ha enviado.",
      reportError: "No se pudo enviar la denuncia. Inténtalo más tarde.",
      moreFrom: (player) => `Más construcciones de ${player}`,
      seeAllFrom: (player) => `Todas las construcciones de ${player}`,
      ctaTitle: "¿Quieres ver tu construcción aquí?",
      ctaBody: "Juega a Build Battle en Cookie Build: recibes un tema y unos minutos para construir. Al final de la partida, tu construcción aparece aquí automáticamente.",
      ctaButton: "Descubrir Build Battle",
      ctaJoin: "Cómo entrar al servidor",
      unavailable: "No se pudo cargar esta construcción en este momento.",
    },
    viewer: {
      label: (theme, player) => `Vista 3D de «${theme}» de ${player}`,
      loading: "Cargando la construcción en 3D…",
      error: "No se pudo cargar la vista 3D.",
      webglFallback: "El 3D no está disponible en este dispositivo; aquí tienes una imagen de la construcción.",
      reset: "Restablecer vista",
      screenshot: "Guardar una captura",
      fullscreen: "Pantalla completa",
      exitFullscreen: "Salir de pantalla completa",
      pause: "Detener la rotación",
      play: "Rotación automática",
      keyboardHelp: "Arrastra para girar, pellizca o usa la rueda para hacer zoom. Teclado: flechas para girar, + y − para el zoom, 0 para restablecer.",
      open3d: "Ver en 3D",
    },
    home: { title: "Lo mejor de la semana", intro: "Las construcciones de Build Battle con más me gusta de la semana.", all: "Ver la galería" },
    landing: {
      title: "Tus construcciones en 3D",
      body: "Cada construcción se guarda al final de la partida. Explora las mejores en 3D, dales me gusta y comparte las tuyas con tus amigos.",
      cta: "Abrir la galería de Build Battle",
    },
  },
  hi: {
    seoTitle: "Build Battle गैलरी: सबसे बेहतरीन Minecraft बिल्ड | Cookie Build",
    seoDescription: "Cookie Build खिलाड़ियों के सबसे बेहतरीन Build Battle बिल्ड 3D में देखें: हफ़्ते, महीने और अब तक के बेस्ट, साथ ही सबसे नए बिल्ड।",
    eyebrow: "Build Battle",
    title: "Build Battle गैलरी",
    intro: "हर Build Battle बिल्ड मैच खत्म होने पर यहाँ आ जाता है। उन्हें 3D में घुमाएँ, अपने पसंदीदा बिल्ड को लाइक करें और शेयर करें। हर हफ़्ते सबसे ज़्यादा लाइक वाले 3 बिल्ड कॉइन जीतते हैं!",
    tabsLabel: "बिल्ड क्रम से लगाएँ",
    tabs: { week: "हफ़्ते के बेस्ट", month: "महीने के बेस्ट", all: "अब तक के बेस्ट", recent: "नए" },
    loadMore: "और देखें",
    loading: "बिल्ड लोड हो रहे हैं…",
    empty: "यहाँ अभी कोई बिल्ड नहीं है। Build Battle का एक मैच खेलें, हो सकता है आपका बिल्ड पहला हो!",
    emptyCta: "कैसे खेलें",
    error: "अभी गैलरी लोड नहीं हो सकी।",
    retry: "फिर से कोशिश करें",
    likes: (_count, formatted) => `${formatted} लाइक`,
    by: (player) => `${player} का बिल्ड`,
    cardAlt: (theme, player) => `Build Battle में ${player} का “${theme}” बिल्ड`,
    placement: (place) => (place === 1 ? "विजेता" : `${place}वाँ स्थान`),
    solo: "सोलो",
    detail: {
      seoTitle: (theme, player) => `${player} का “${theme}” – Build Battle | Cookie Build`,
      seoDescription: (theme, player) => `Cookie Build पर ${player} का Build Battle बिल्ड “${theme}” 3D में देखें, फिर उसे लाइक और शेयर करें।`,
      back: "सभी बिल्ड",
      theme: "थीम",
      builtOn: (date) => `${date} को बनाया गया`,
      blocks: (formatted) => `${formatted} ब्लॉक`,
      like: "यह बिल्ड लाइक करें",
      unlike: "अपना लाइक हटाएँ",
      likeError: "आपका लाइक सेव नहीं हो सका। थोड़ी देर में फिर से कोशिश करें।",
      share: "शेयर करें",
      shareTitle: (theme, player) => `${player} का “${theme}”`,
      shareText: (theme, player) => `Cookie Build पर ${player} का “${theme}” बिल्ड देखें!`,
      copyLink: "लिंक कॉपी करें",
      link: "लिंक",
      shareOnX: "X पर शेयर करें",
      shareOnWhatsApp: "WhatsApp पर शेयर करें",
      openImage: "इमेज खोलें",
      report: "रिपोर्ट करें",
      reportTitle: "इस बिल्ड की रिपोर्ट करें",
      reportIntro: "हमें बताएँ कि क्या गलत है। हमारी टीम हर रिपोर्ट की जाँच करती है।",
      reasons: { offensive: "अपमानजनक या नफ़रत भरा", inappropriate: "अनुचित सामग्री", other: "कुछ और" },
      reportSubmit: "रिपोर्ट भेजें",
      reportCancel: "रद्द करें",
      reportThanks: "धन्यवाद, आपकी रिपोर्ट भेज दी गई है।",
      reportError: "रिपोर्ट नहीं भेजी जा सकी। बाद में फिर से कोशिश करें।",
      moreFrom: (player) => `${player} के और बिल्ड`,
      seeAllFrom: (player) => `${player} के सभी बिल्ड`,
      ctaTitle: "क्या आप अपना बिल्ड यहाँ देखना चाहते हैं?",
      ctaBody: "Cookie Build पर Build Battle खेलें: आपको एक थीम और बनाने के लिए कुछ मिनट मिलते हैं। मैच खत्म होते ही आपका बिल्ड अपने-आप यहाँ दिखेगा।",
      ctaButton: "Build Battle के बारे में जानें",
      ctaJoin: "सर्वर से कैसे जुड़ें",
      unavailable: "यह बिल्ड अभी लोड नहीं हो सका।",
    },
    viewer: {
      label: (theme, player) => `${player} के “${theme}” का 3D व्यू`,
      loading: "3D बिल्ड लोड हो रहा है…",
      error: "3D व्यू लोड नहीं हो सका।",
      webglFallback: "इस डिवाइस पर 3D उपलब्ध नहीं है, इसलिए बिल्ड की तस्वीर दिखाई जा रही है।",
      reset: "व्यू रीसेट करें",
      screenshot: "स्क्रीनशॉट सेव करें",
      fullscreen: "फ़ुल स्क्रीन",
      exitFullscreen: "फ़ुल स्क्रीन से बाहर निकलें",
      pause: "घूमना रोकें",
      play: "अपने-आप घुमाएँ",
      keyboardHelp: "घुमाने के लिए ड्रैग करें, ज़ूम के लिए पिंच या स्क्रॉल करें। कीबोर्ड: ऐरो कीज़ से घुमाएँ, + और − से ज़ूम, 0 से रीसेट।",
      open3d: "3D में देखें",
    },
    home: { title: "हफ़्ते के बेस्ट बिल्ड", intro: "इस हफ़्ते सबसे ज़्यादा लाइक किए गए Build Battle बिल्ड।", all: "गैलरी खोलें" },
    landing: {
      title: "आपके बिल्ड, 3D में",
      body: "हर बिल्ड मैच के अंत में सेव हो जाता है। सबसे अच्छे बिल्ड 3D में देखें, उन्हें लाइक करें और अपने बिल्ड दोस्तों के साथ शेयर करें।",
      cta: "Build Battle गैलरी खोलें",
    },
  },
  "pt-BR": {
    seoTitle: "Galeria do Build Battle: as melhores construções de Minecraft | Cookie Build",
    seoDescription: "Veja em 3D as melhores construções de Build Battle dos jogadores do Cookie Build: melhores da semana, do mês, de todos os tempos e as mais recentes.",
    eyebrow: "Build Battle",
    title: "Galeria do Build Battle",
    intro: "Toda construção do Build Battle chega aqui no fim da partida. Gire em 3D, curta suas favoritas e compartilhe. Toda semana, as 3 construções mais curtidas ganham moedas!",
    tabsLabel: "Ordenar construções",
    tabs: { week: "Melhores da semana", month: "Melhores do mês", all: "De todos os tempos", recent: "Recentes" },
    loadMore: "Carregar mais",
    loading: "Carregando construções…",
    empty: "Ainda não há construções aqui. Jogue uma partida de Build Battle e a sua pode ser a primeira!",
    emptyCta: "Como jogar",
    error: "Não foi possível carregar a galeria agora.",
    retry: "Tentar de novo",
    likes: (count, formatted) => `${formatted} ${count === 1 ? "curtida" : "curtidas"}`,
    by: (player) => `por ${player}`,
    cardAlt: (theme, player) => `Construção “${theme}” de ${player} no Build Battle`,
    placement: (place) => (place === 1 ? "Vencedor" : `${place}º lugar`),
    solo: "Solo",
    detail: {
      seoTitle: (theme, player) => `“${theme}” por ${player} – Build Battle | Cookie Build`,
      seoDescription: (theme, player) => `Explore em 3D a construção “${theme}” de ${player} no Build Battle do Cookie Build, curta e compartilhe.`,
      back: "Todas as construções",
      theme: "Tema",
      builtOn: (date) => `Construída em ${date}`,
      blocks: (formatted) => `${formatted} blocos`,
      like: "Curtir esta construção",
      unlike: "Remover sua curtida",
      likeError: "Não foi possível salvar sua curtida. Tente de novo em instantes.",
      share: "Compartilhar",
      shareTitle: (theme, player) => `“${theme}” por ${player}`,
      shareText: (theme, player) => `Olha a construção “${theme}” de ${player} no Cookie Build!`,
      copyLink: "Copiar link",
      link: "Link",
      shareOnX: "Compartilhar no X",
      shareOnWhatsApp: "Compartilhar no WhatsApp",
      openImage: "Abrir a imagem",
      report: "Denunciar",
      reportTitle: "Denunciar esta construção",
      reportIntro: "Conte o que está errado. Nossa equipe analisa cada denúncia.",
      reasons: { offensive: "Ofensiva ou de ódio", inappropriate: "Conteúdo impróprio", other: "Outro motivo" },
      reportSubmit: "Enviar denúncia",
      reportCancel: "Cancelar",
      reportThanks: "Obrigado, sua denúncia foi enviada.",
      reportError: "Não foi possível enviar a denúncia. Tente mais tarde.",
      moreFrom: (player) => `Mais construções de ${player}`,
      seeAllFrom: (player) => `Todas as construções de ${player}`,
      ctaTitle: "Quer ver sua construção aqui?",
      ctaBody: "Jogue Build Battle no Cookie Build: você recebe um tema e alguns minutos para construir. No fim da partida, sua construção aparece aqui automaticamente.",
      ctaButton: "Conhecer o Build Battle",
      ctaJoin: "Como entrar no servidor",
      unavailable: "Não foi possível carregar esta construção agora.",
    },
    viewer: {
      label: (theme, player) => `Visualização 3D de “${theme}” por ${player}`,
      loading: "Carregando a construção em 3D…",
      error: "Não foi possível carregar a visualização 3D.",
      webglFallback: "O 3D não está disponível neste aparelho; veja uma imagem da construção.",
      reset: "Redefinir visualização",
      screenshot: "Salvar captura de tela",
      fullscreen: "Tela cheia",
      exitFullscreen: "Sair da tela cheia",
      pause: "Parar a rotação",
      play: "Girar automaticamente",
      keyboardHelp: "Arraste para girar, faça pinça ou role para dar zoom. Teclado: setas giram, + e − dão zoom, 0 redefine.",
      open3d: "Ver em 3D",
    },
    home: { title: "Melhores da semana", intro: "As construções de Build Battle mais curtidas da semana.", all: "Abrir a galeria" },
    landing: {
      title: "Suas construções em 3D",
      body: "Cada construção é salva no fim da partida. Explore as melhores em 3D, curta e compartilhe as suas com os amigos.",
      cta: "Abrir a galeria do Build Battle",
    },
  },
};
