import type { SiteLocaleCode } from "./site-locales";

export const gameUiCopy = {
  en: { beta: "Public beta", back: "Back to updates", play: "Play with friends", connect: "Connect to Cookie Build, then enter the command in chat or choose the mode in the game menu.", join: "Join", leave: "Leave the queue or match with /leave. Join the same mode before the countdown starts.", gold: "Gold and points per second", ingots: "ingots", image: "Real Minecraft world render", discover: "Discover the game", rules: "Read the beta rules" },
  fr: { beta: "Bêta publique", back: "Retour aux actualités", play: "Jouer avec tes amis", connect: "Connecte-toi à Cookie Build, puis saisis la commande dans le chat ou choisis le mode dans le menu des jeux.", join: "Rejoindre", leave: "Pour quitter la file ou la partie : /leave. Retrouvez-vous dans le même mode avant le début du compte à rebours.", gold: "Or et points par seconde", ingots: "lingots", image: "Rendu du vrai monde Minecraft", discover: "Découvrir le jeu", rules: "Lire les règles de la bêta" },
  de: { beta: "Öffentliche Beta", back: "Zurück zu Neuigkeiten", play: "Mit Freunden spielen", connect: "Verbinde dich mit Cookie Build und gib den Befehl im Chat ein oder wähle das Spiel im Menü.", join: "Beitreten", leave: "Verlasse Warteschlange oder Partie mit /leave. Tretet demselben Spiel bei, bevor der Countdown beginnt.", gold: "Gold und Punkte pro Sekunde", ingots: "Barren", image: "Ansicht der echten Minecraft-Welt", discover: "Spiel entdecken", rules: "Betaregeln lesen" },
  it: { beta: "Beta pubblica", back: "Torna alle notizie", play: "Gioca con gli amici", connect: "Collegati a Cookie Build, poi scrivi il comando in chat o scegli la modalità nel menu dei giochi.", join: "Entra", leave: "Lascia la coda o la partita con /leave. Entrate nella stessa modalità prima dell’inizio del conto alla rovescia.", gold: "Oro e punti al secondo", ingots: "lingotti", image: "Vista del vero mondo Minecraft", discover: "Scopri il gioco", rules: "Leggi le regole della beta" },
  bg: { beta: "Публична бета", back: "Обратно към новините", play: "Играй с приятели", connect: "Свържи се с Cookie Build, после въведи командата в чата или избери режима от менюто.", join: "Присъединяване", leave: "Напусни опашката или мача с /leave. Влезте в един и същ режим преди началото на отброяването.", gold: "Злато и точки в секунда", ingots: "кюлчета", image: "Изглед на истинския Minecraft свят", discover: "Разгледай играта", rules: "Прочети правилата на бетата" },
  es: { beta: "Beta pública", back: "Volver a las novedades", play: "Juega con tus amigos", connect: "Conéctate a Cookie Build, escribe el comando en el chat o elige el modo en el menú de juegos.", join: "Entrar", leave: "Sal de la cola o de la partida con /leave. Entren al mismo modo antes de que empiece la cuenta regresiva.", gold: "Oro y puntos por segundo", ingots: "lingotes", image: "Vista del mundo real de Minecraft", discover: "Descubre el juego", rules: "Leer las reglas de la beta" },
  hi: { beta: "सार्वजनिक बीटा", back: "समाचारों पर लौटें", play: "दोस्तों के साथ खेलें", connect: "Cookie Build से जुड़ें, फिर चैट में कमांड लिखें या गेम मेनू से मोड चुनें।", join: "जुड़ें", leave: "/leave से कतार या मैच छोड़ें। उलटी गिनती शुरू होने से पहले सभी एक ही मोड में जुड़ें।", gold: "सोना और प्रति सेकंड अंक", ingots: "सिल्ले", image: "असली Minecraft दुनिया का दृश्य", discover: "गेम जानें", rules: "बीटा के नियम पढ़ें" },
  "pt-BR": { beta: "Beta pública", back: "Voltar às novidades", play: "Jogue com seus amigos", connect: "Conecte-se ao Cookie Build e digite o comando no chat ou escolha o modo no menu de jogos.", join: "Entrar", leave: "Saia da fila ou da partida com /leave. Entrem no mesmo modo antes de começar a contagem regressiva.", gold: "Ouro e pontos por segundo", ingots: "barras", image: "Vista do mundo real do Minecraft", discover: "Conheça o jogo", rules: "Ler as regras da beta" },
} satisfies Record<SiteLocaleCode, Record<string, string>>;
