export const STATUS_COPY = {
  de: {
    "locale": "de-DE",
    "badge": "Live-Netzwerkstatus",
    "title": "Cookie Build Status",
    "intro": "Java und Bedrock werden unabhängig geprüft. Eine nicht verfügbare Prüfung ist kein bestätigter Ausfall. Ein erreichbares Netzwerk kann tatsächlich null Spieler haben.",
    "currentStatus": "Aktueller Status",
    "checking": "Beide Editionen werden geprüft…",
    "noRecentCheck": "Keine aktuelle Prüfung verfügbar.",
    "lastChecked": "Zuletzt geprüft",
    "refresh": "Prüfung aktualisieren",
    "javaEdition": "Java Edition",
    "bedrockEdition": "Bedrock Edition",
    "playersReported": "Gemeldete Spieler",
    "version": "Version",
    "notReported": "Nicht gemeldet",
    "online": "Online",
    "offline": "Offline",
    "checkUnavailable": "Prüfung nicht verfügbar",
    "checksUnavailable": "Die öffentlichen Statusprüfungen sind vorübergehend nicht verfügbar. Das allein bestätigt keinen Serverausfall.",
    "bothOnlineZero": "Beide Editionen sind online · aktuell 0 Spieler",
    "partial": "Teilweise verfügbar · siehe Details oben",
    "partialNoOnline": "Teilweiser Status · keine Edition bestätigt online",
    "outageUnconfirmed": "Statusprüfung nicht verfügbar · Ausfall nicht bestätigt",
    "networkOffline": "Das Minecraft-Netzwerk ist derzeit offline",
    "port": "Port",
    "needHelp": "Brauchst du Hilfe?",
    "helpText": "Prüfe Edition und Adresse. Kontaktiere den Support, falls das Problem bestehen bleibt.",
    "openSupport": "Support öffnen",
    "howTitle": "So funktionieren die Prüfungen",
    "howText": "Diese Seite nutzt kurzzeitig zwischengespeicherte öffentliche Minecraft-Protokollprüfungen. Java und Bedrock teilen dasselbe Cookie-Build-Netzwerk. Die Zusammenfassung zeigt deshalb die größere gemeldete Spielerzahl statt beide Werte zu addieren und Spieler möglicherweise doppelt zu zählen.",
    playersOnline: (players: number) => `${players} Spieler online`
  },
  it: {
    "locale": "it-IT",
    "badge": "Stato della rete in diretta",
    "title": "Stato di Cookie Build",
    "intro": "Controlli indipendenti per Java e Bedrock. Un controllo non disponibile è distinto da un guasto confermato. Una rete online può avere davvero zero giocatori connessi.",
    "currentStatus": "Stato attuale",
    "checking": "Controllo di entrambe le edizioni…",
    "noRecentCheck": "Nessun controllo recente disponibile.",
    "lastChecked": "Ultimo controllo",
    "refresh": "Aggiorna controlli",
    "javaEdition": "Edizione Java",
    "bedrockEdition": "Edizione Bedrock",
    "playersReported": "Giocatori segnalati",
    "version": "Versione",
    "notReported": "Non segnalata",
    "online": "Online",
    "offline": "Offline",
    "checkUnavailable": "Controllo non disponibile",
    "checksUnavailable": "I controlli pubblici sono temporaneamente indisponibili. Questo non conferma, da solo, un guasto del server.",
    "bothOnlineZero": "Entrambe le edizioni sono online · 0 giocatori ora",
    "partial": "Disponibilità parziale · controlla i dettagli sopra",
    "partialNoOnline": "Stato parziale · nessuna edizione confermata online",
    "outageUnconfirmed": "Controlli indisponibili · guasto non confermato",
    "networkOffline": "La rete Minecraft è attualmente offline",
    "port": "Porta",
    "needHelp": "Serve aiuto?",
    "helpText": "Controlla edizione e indirizzo, poi contatta l’assistenza se il problema continua.",
    "openSupport": "Apri assistenza",
    "howTitle": "Come funzionano i controlli",
    "howText": "La pagina utilizza controlli pubblici del protocollo Minecraft con una breve durata di validità. Java e Bedrock condividono la stessa rete Cookie Build: il riepilogo mostra il maggiore dei conteggi segnalati, anziché sommarli e rischiare di contare due volte un giocatore.",
    playersOnline: (players: number) => `${players} ${players === 1 ? "giocatore" : "giocatori"} online`
  },
  bg: {
    "locale": "bg-BG",
    "badge": "Състояние на мрежата на живо",
    "title": "Състояние на Cookie Build",
    "intro": "Независими проверки за Java и Bedrock. Недостъпната проверка се показва отделно от потвърдено прекъсване. Онлайн мрежата може действително да има нула свързани играчи.",
    "currentStatus": "Текущо състояние",
    "checking": "Проверка на двете издания…",
    "noRecentCheck": "Няма скорошна проверка.",
    "lastChecked": "Последна проверка",
    "refresh": "Обнови проверките",
    "javaEdition": "Издание Java",
    "bedrockEdition": "Издание Bedrock",
    "playersReported": "Отчетени играчи",
    "version": "Версия",
    "notReported": "Не е отчетена",
    "online": "Онлайн",
    "offline": "Офлайн",
    "checkUnavailable": "Проверката е недостъпна",
    "checksUnavailable": "Публичните проверки временно не са достъпни. Само това не потвърждава прекъсване на сървъра.",
    "bothOnlineZero": "Двете издания са онлайн · 0 играчи в момента",
    "partial": "Частична достъпност · виж подробностите по-горе",
    "partialNoOnline": "Частично състояние · няма потвърдено онлайн издание",
    "outageUnconfirmed": "Проверките са недостъпни · прекъсването не е потвърдено",
    "networkOffline": "Minecraft мрежата в момента е офлайн",
    "port": "Порт",
    "needHelp": "Нужда от помощ?",
    "helpText": "Провери изданието и адреса. Свържи се с поддръжката, ако проблемът продължава.",
    "openSupport": "Отвори поддръжката",
    "howTitle": "Как работят проверките",
    "howText": "Страницата използва публични проверки на протокола Minecraft с кратък срок на валидност. Java и Bedrock споделят мрежата на Cookie Build. Затова обобщението показва по-големия отчетен брой играчи, вместо да събира двата броя и евентуално да брои един играч два пъти.",
    playersOnline: (players: number) => `${players} играчи онлайн`
  },
  hi: {
    "locale": "hi-IN",
    "badge": "नेटवर्क की लाइव स्थिति",
    "title": "Cookie Build की स्थिति",
    "intro": "Java और Bedrock की अलग-अलग जाँच। अनुपलब्ध जाँच को पुष्ट सेवा बंद होने से अलग दिखाया जाता है। ऑनलाइन नेटवर्क पर सच में शून्य खिलाड़ी भी हो सकते हैं।",
    "currentStatus": "वर्तमान स्थिति",
    "checking": "दोनों संस्करणों की जाँच हो रही है…",
    "noRecentCheck": "हाल की कोई जाँच उपलब्ध नहीं है।",
    "lastChecked": "आखिरी जाँच",
    "refresh": "फिर से जाँचें",
    "javaEdition": "Java संस्करण",
    "bedrockEdition": "Bedrock संस्करण",
    "playersReported": "बताए गए खिलाड़ी",
    "version": "संस्करण",
    "notReported": "जानकारी नहीं मिली",
    "online": "ऑनलाइन",
    "offline": "ऑफलाइन",
    "checkUnavailable": "जाँच उपलब्ध नहीं",
    "checksUnavailable": "सार्वजनिक स्थिति जाँच अस्थायी रूप से उपलब्ध नहीं है। इससे अकेले सर्वर बंद होने की पुष्टि नहीं होती।",
    "bothOnlineZero": "दोनों संस्करण ऑनलाइन हैं · अभी 0 खिलाड़ी",
    "partial": "आंशिक उपलब्धता · ऊपर संस्करण का विवरण देखें",
    "partialNoOnline": "आंशिक स्थिति · किसी संस्करण के ऑनलाइन होने की पुष्टि नहीं",
    "outageUnconfirmed": "जाँच अनुपलब्ध · सेवा बंद होने की पुष्टि नहीं",
    "networkOffline": "Minecraft नेटवर्क अभी ऑफलाइन है",
    "port": "पोर्ट",
    "needHelp": "मदद चाहिए?",
    "helpText": "अपना संस्करण और पता जाँचें। समस्या जारी रहने पर सहायता से संपर्क करें।",
    "openSupport": "सहायता खोलें",
    "howTitle": "ये जाँच कैसे काम करती हैं",
    "howText": "यह पेज थोड़े समय तक मान्य सार्वजनिक Minecraft प्रोटोकॉल जाँच का उपयोग करता है। Java और Bedrock एक ही Cookie Build नेटवर्क साझा करते हैं। इसलिए सारांश दोनों गिनतियों को जोड़कर किसी खिलाड़ी को दो बार गिनने के बजाय बड़ी बताई गई संख्या दिखाता है।",
    playersOnline: (players: number) => `${players} खिलाड़ी ऑनलाइन`
  },
  en: {
    locale: "en",
    badge: "Live network status",
    title: "Cookie Build status",
    intro: "Independent checks for Java and Bedrock. An unavailable check is shown separately from a confirmed outage, and an online network can genuinely have zero players connected.",
    currentStatus: "Current status",
    checking: "Checking both editions…",
    noRecentCheck: "No recent check is available.",
    lastChecked: "Last checked",
    refresh: "Refresh checks",
    javaEdition: "Java Edition",
    bedrockEdition: "Bedrock Edition",
    playersReported: "Players reported",
    version: "Version",
    notReported: "Not reported",
    online: "Online",
    offline: "Offline",
    checkUnavailable: "Check unavailable",
    checksUnavailable: "The public status checks are temporarily unavailable. This does not by itself confirm a server outage.",
    bothOnlineZero: "Both editions are online · 0 players right now",
    playersOnline: (players: number) => `${players} ${players === 1 ? "player" : "players"} online`,
    partial: "Partial availability · check the edition details above",
    partialNoOnline: "Partial status · no edition is confirmed online",
    outageUnconfirmed: "Status checks unavailable · outage not confirmed",
    networkOffline: "The Minecraft network is currently offline",
    port: "Port",
    needHelp: "Need help?",
    helpText: "Check your edition and address, then contact support if the issue continues.",
    openSupport: "Open support",
    howTitle: "How these checks work",
    howText: "The page uses short-lived public Minecraft protocol checks. Java and Bedrock share the same Cookie Build network, so the headline uses the larger reported count instead of adding both figures and potentially counting a player twice.",
  },
  fr: {
    locale: "fr-FR",
    badge: "État du réseau en direct",
    title: "État de Cookie Build",
    intro: "Java et Bedrock sont vérifiés séparément. Une vérification indisponible est distinguée d’une panne confirmée, et un réseau en ligne peut réellement compter zéro joueur connecté.",
    currentStatus: "État actuel",
    checking: "Vérification des deux éditions…",
    noRecentCheck: "Aucune vérification récente n’est disponible.",
    lastChecked: "Dernière vérification",
    refresh: "Actualiser",
    javaEdition: "Édition Java",
    bedrockEdition: "Édition Bedrock",
    playersReported: "Joueurs annoncés",
    version: "Version",
    notReported: "Non indiquée",
    online: "En ligne",
    offline: "Hors ligne",
    checkUnavailable: "Vérification indisponible",
    checksUnavailable: "Les vérifications publiques sont temporairement indisponibles. Cela ne confirme pas à lui seul une panne du serveur.",
    bothOnlineZero: "Les deux éditions sont en ligne · 0 joueur actuellement",
    playersOnline: (players: number) => `${players} joueur${players === 1 ? "" : "s"} en ligne`,
    partial: "Disponibilité partielle · consulte les détails de chaque édition",
    partialNoOnline: "État partiel · aucune édition n’est confirmée en ligne",
    outageUnconfirmed: "Vérifications indisponibles · panne non confirmée",
    networkOffline: "Le réseau Minecraft est actuellement hors ligne",
    port: "Port",
    needHelp: "Besoin d’aide ?",
    helpText: "Vérifie ton édition et l’adresse, puis contacte le support si le problème continue.",
    openSupport: "Ouvrir le support",
    howTitle: "Fonctionnement des vérifications",
    howText: "Cette page utilise de brèves vérifications publiques du protocole Minecraft. Java et Bedrock partagent le même réseau Cookie Build : le total retient donc la valeur la plus élevée au lieu d’additionner les deux et de risquer de compter un joueur deux fois.",
  },
  es: {
    locale: "es-ES",
    badge: "Estado de la red en directo",
    title: "Estado de Cookie Build",
    intro: "Java y Bedrock se comprueban por separado. Una comprobación no disponible se distingue de una caída confirmada, y una red online puede tener realmente cero jugadores conectados.",
    currentStatus: "Estado actual",
    checking: "Comprobando las dos ediciones…",
    noRecentCheck: "No hay ninguna comprobación reciente disponible.",
    lastChecked: "Última comprobación",
    refresh: "Actualizar comprobaciones",
    javaEdition: "Edición Java",
    bedrockEdition: "Edición Bedrock",
    playersReported: "Jugadores indicados",
    version: "Versión",
    notReported: "No indicada",
    online: "Online",
    offline: "Offline",
    checkUnavailable: "Comprobación no disponible",
    checksUnavailable: "Las comprobaciones públicas no están disponibles temporalmente. Esto no confirma por sí solo una caída del servidor.",
    bothOnlineZero: "Las dos ediciones están online · 0 jugadores ahora",
    playersOnline: (players: number) => `${players} ${players === 1 ? "jugador online" : "jugadores online"}`,
    partial: "Disponibilidad parcial · consulta los detalles de cada edición",
    partialNoOnline: "Estado parcial · ninguna edición está confirmada como online",
    outageUnconfirmed: "Comprobaciones no disponibles · caída no confirmada",
    networkOffline: "La red de Minecraft está offline en este momento",
    port: "Puerto",
    needHelp: "¿Necesitas ayuda?",
    helpText: "Comprueba tu edición y la dirección. Si el problema continúa, contacta con soporte.",
    openSupport: "Abrir soporte",
    howTitle: "Cómo funcionan las comprobaciones",
    howText: "La página usa comprobaciones públicas y breves del protocolo de Minecraft. Java y Bedrock comparten la misma red de Cookie Build, por lo que el resumen utiliza el número más alto en vez de sumar ambos y contar posiblemente a una persona dos veces.",
  },
  "pt-BR": {
    locale: "pt-BR",
    badge: "Status da rede ao vivo",
    title: "Status do Cookie Build",
    intro: "Java e Bedrock são verificados separadamente. Uma verificação indisponível aparece de forma diferente de uma queda confirmada, e uma rede online pode realmente estar com zero jogadores conectados.",
    currentStatus: "Status atual",
    checking: "Verificando as duas edições…",
    noRecentCheck: "Nenhuma verificação recente está disponível.",
    lastChecked: "Última verificação",
    refresh: "Atualizar verificações",
    javaEdition: "Edição Java",
    bedrockEdition: "Edição Bedrock",
    playersReported: "Jogadores informados",
    version: "Versão",
    notReported: "Não informada",
    online: "Online",
    offline: "Offline",
    checkUnavailable: "Verificação indisponível",
    checksUnavailable: "As verificações públicas estão temporariamente indisponíveis. Isso, por si só, não confirma uma queda do servidor.",
    bothOnlineZero: "As duas edições estão online · 0 jogadores agora",
    playersOnline: (players: number) => `${players} ${players === 1 ? "jogador online" : "jogadores online"}`,
    partial: "Disponibilidade parcial · confira os detalhes de cada edição",
    partialNoOnline: "Status parcial · nenhuma edição está confirmada como online",
    outageUnconfirmed: "Verificações indisponíveis · queda não confirmada",
    networkOffline: "A rede Minecraft está offline no momento",
    port: "Porta",
    needHelp: "Precisa de ajuda?",
    helpText: "Confirme sua edição e o endereço. Se o problema continuar, fale com o suporte.",
    openSupport: "Abrir suporte",
    howTitle: "Como as verificações funcionam",
    howText: "A página usa verificações públicas e breves do protocolo Minecraft. Java e Bedrock compartilham a mesma rede Cookie Build, então o resumo usa o maior número informado em vez de somar os dois e possivelmente contar uma pessoa duas vezes.",
  },
} as const;
