// Generated by scripts/generate-bb-theme-names.mjs from the BuildBattles plugin
// bundles (bb.theme.name.*). Do not edit by hand.
export const BUILDBATTLE_THEME_NAMES: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  "airplane": {
    "bg": "Самолет",
    "de": "Flugzeug",
    "en": "Airplane",
    "es": "Avión",
    "fr": "Avion",
    "hi": "हवाई जहाज़",
    "pa": "ਹਵਾਈ ਜਹਾਜ਼",
    "pt-BR": "Avião"
  },
  "alien": {
    "bg": "Извънземно",
    "de": "Alien",
    "en": "Alien",
    "es": "Extraterrestre",
    "fr": "Extraterrestre",
    "hi": "एलियन",
    "pa": "ਏਲੀਅਨ",
    "pt-BR": "Alienígena"
  },
  "animals": {
    "bg": "Животни",
    "de": "Tiere",
    "en": "Animals",
    "es": "Animales",
    "fr": "Animaux",
    "hi": "जानवर",
    "pa": "ਜਾਨਵਰ",
    "pt-BR": "Animais"
  },
  "basketball": {
    "bg": "Баскетбол",
    "de": "Basketball",
    "en": "Basketball",
    "es": "Baloncesto",
    "fr": "Basket-ball",
    "hi": "बास्केटबॉल",
    "pa": "ਬਾਸਕਟਬਾਲ",
    "pt-BR": "Basquete"
  },
  "birds": {
    "bg": "Птици",
    "de": "Vögel",
    "en": "Birds",
    "es": "Pájaros",
    "fr": "Oiseaux",
    "hi": "पक्षी",
    "pa": "ਪੰਛੀ",
    "pt-BR": "Pássaros"
  },
  "camping": {
    "bg": "Къмпинг",
    "de": "Camping",
    "en": "Camping",
    "es": "Acampada",
    "fr": "Camping",
    "hi": "कैंपिंग",
    "pa": "ਕੈਂਪਿੰਗ",
    "pt-BR": "Acampamento"
  },
  "candle": {
    "bg": "Свещ",
    "de": "Kerze",
    "en": "Candle",
    "es": "Vela",
    "fr": "Bougie",
    "hi": "मोमबत्ती",
    "pa": "ਮੋਮਬੱਤੀ",
    "pt-BR": "Vela"
  },
  "candy": {
    "bg": "Бонбони",
    "de": "Süßigkeiten",
    "en": "Candy",
    "es": "Dulces",
    "fr": "Bonbons",
    "hi": "कैंडी",
    "pa": "ਮਿਠਾਈ",
    "pt-BR": "Doces"
  },
  "car": {
    "bg": "Кола",
    "de": "Auto",
    "en": "Car",
    "es": "Coche",
    "fr": "Voiture",
    "hi": "कार",
    "pa": "ਕਾਰ",
    "pt-BR": "Carro"
  },
  "clock": {
    "bg": "Часовник",
    "de": "Uhr",
    "en": "Clock",
    "es": "Reloj",
    "fr": "Horloge",
    "hi": "घड़ी",
    "pa": "ਘੜੀ",
    "pt-BR": "Relógio"
  },
  "console": {
    "bg": "Конзола",
    "de": "Konsole",
    "en": "Console",
    "es": "Consola",
    "fr": "Console",
    "hi": "कंसोल",
    "pa": "ਕੰਸੋਲ",
    "pt-BR": "Console"
  },
  "desk": {
    "bg": "Бюро",
    "de": "Schreibtisch",
    "en": "Desk",
    "es": "Escritorio",
    "fr": "Bureau",
    "hi": "मेज़",
    "pa": "ਮੇਜ਼",
    "pt-BR": "Escrivaninha"
  },
  "dragon": {
    "bg": "Дракон",
    "de": "Drache",
    "en": "Dragon",
    "es": "Dragón",
    "fr": "Dragon",
    "hi": "ड्रैगन",
    "pa": "ਡ੍ਰੈਗਨ",
    "pt-BR": "Dragão"
  },
  "emoji": {
    "bg": "Емоджи",
    "de": "Emoji",
    "en": "Emoji",
    "es": "Emoji",
    "fr": "Emoji",
    "hi": "इमोजी",
    "pa": "ਇਮੋਜੀ",
    "pt-BR": "Emoji"
  },
  "farm": {
    "bg": "Ферма",
    "de": "Bauernhof",
    "en": "Farm",
    "es": "Granja",
    "fr": "Ferme",
    "hi": "खेत",
    "pa": "ਖੇਤ",
    "pt-BR": "Fazenda"
  },
  "fast_food": {
    "bg": "Бързо хранене",
    "de": "Fast Food",
    "en": "Fast Food",
    "es": "Comida rápida",
    "fr": "Restauration rapide",
    "hi": "फ़ास्ट फ़ूड",
    "pa": "ਫ਼ਾਸਟ ਫ਼ੂਡ",
    "pt-BR": "Fast-food"
  },
  "free_style": {
    "bg": "Свободен стил",
    "de": "Freestyle",
    "en": "Free Style",
    "es": "Estilo libre",
    "fr": "Style libre",
    "hi": "मुक्त शैली",
    "pa": "ਫ਼੍ਰੀ ਸਟਾਈਲ",
    "pt-BR": "Estilo livre"
  },
  "halloween": {
    "bg": "Хелоуин",
    "de": "Halloween",
    "en": "Halloween",
    "es": "Halloween",
    "fr": "Halloween",
    "hi": "हैलोवीन",
    "pa": "ਹੈਲੋਵੀਨ",
    "pt-BR": "Halloween"
  },
  "house": {
    "bg": "Къща",
    "de": "Haus",
    "en": "House",
    "es": "Casa",
    "fr": "Maison",
    "hi": "घर",
    "pa": "ਘਰ",
    "pt-BR": "Casa"
  },
  "ice_cream": {
    "bg": "Сладолед",
    "de": "Eiscreme",
    "en": "Ice Cream",
    "es": "Helado",
    "fr": "Glace",
    "hi": "आइसक्रीम",
    "pa": "ਆਈਸਕ੍ਰੀਮ",
    "pt-BR": "Sorvete"
  },
  "lighthouse": {
    "bg": "Фар",
    "de": "Leuchtturm",
    "en": "Lighthouse",
    "es": "Faro",
    "fr": "Phare",
    "hi": "प्रकाशस्तंभ",
    "pa": "ਲਾਈਟਹਾਊਸ",
    "pt-BR": "Farol"
  },
  "magic": {
    "bg": "Магия",
    "de": "Magie",
    "en": "Magic",
    "es": "Magia",
    "fr": "Magie",
    "hi": "जादू",
    "pa": "ਜਾਦੂ",
    "pt-BR": "Magia"
  },
  "mario": {
    "bg": "Mario",
    "de": "Mario",
    "en": "Mario",
    "es": "Mario",
    "fr": "Mario",
    "hi": "Mario",
    "pa": "ਮਾਰੀਓ",
    "pt-BR": "Mario"
  },
  "maze": {
    "bg": "Лабиринт",
    "de": "Labyrinth",
    "en": "Maze",
    "es": "Laberinto",
    "fr": "Labyrinthe",
    "hi": "भूलभुलैया",
    "pa": "ਭੁੱਲ-ਭੁਲੱਈਆ",
    "pt-BR": "Labirinto"
  },
  "minions": {
    "bg": "Миньони",
    "de": "Minions",
    "en": "Minions",
    "es": "Minions",
    "fr": "Minions",
    "hi": "मिनियन्स",
    "pa": "ਮਿਨੀਅਨਜ਼",
    "pt-BR": "Minions"
  },
  "nintendo": {
    "bg": "Nintendo",
    "de": "Nintendo",
    "en": "Nintendo",
    "es": "Nintendo",
    "fr": "Nintendo",
    "hi": "Nintendo",
    "pa": "ਨਿਨਟੈਂਡੋ",
    "pt-BR": "Nintendo"
  },
  "pixel_art": {
    "bg": "Пиксел арт",
    "de": "Pixel-Art",
    "en": "Pixel Art",
    "es": "Pixel art",
    "fr": "Pixel art",
    "hi": "पिक्सेल कला",
    "pa": "ਪਿਕਸਲ ਆਰਟ",
    "pt-BR": "Pixel art"
  },
  "pizza": {
    "bg": "Пица",
    "de": "Pizza",
    "en": "Pizza",
    "es": "Pizza",
    "fr": "Pizza",
    "hi": "पिज़्ज़ा",
    "pa": "ਪੀਜ਼ਾ",
    "pt-BR": "Pizza"
  },
  "pokemon": {
    "bg": "Pokémon",
    "de": "Pokémon",
    "en": "Pokémon",
    "es": "Pokémon",
    "fr": "Pokémon",
    "hi": "Pokémon",
    "pa": "ਪੋਕੇਮੋਨ",
    "pt-BR": "Pokémon"
  },
  "pyramid": {
    "bg": "Пирамида",
    "de": "Pyramide",
    "en": "Pyramid",
    "es": "Pirámide",
    "fr": "Pyramide",
    "hi": "पिरामिड",
    "pa": "ਪਿਰਾਮਿਡ",
    "pt-BR": "Pirâmide"
  },
  "rabbit": {
    "bg": "Заек",
    "de": "Hase",
    "en": "Rabbit",
    "es": "Conejo",
    "fr": "Lapin",
    "hi": "खरगोश",
    "pa": "ਖ਼ਰਗੋਸ਼",
    "pt-BR": "Coelho"
  },
  "restaurant": {
    "bg": "Ресторант",
    "de": "Restaurant",
    "en": "Restaurant",
    "es": "Restaurante",
    "fr": "Restaurant",
    "hi": "रेस्तरां",
    "pa": "ਰੈਸਟੋਰੈਂਟ",
    "pt-BR": "Restaurante"
  },
  "rocket": {
    "bg": "Ракета",
    "de": "Rakete",
    "en": "Rocket",
    "es": "Cohete",
    "fr": "Fusée",
    "hi": "रॉकेट",
    "pa": "ਰਾਕੇਟ",
    "pt-BR": "Foguete"
  },
  "ruins": {
    "bg": "Руини",
    "de": "Ruinen",
    "en": "Ruins",
    "es": "Ruinas",
    "fr": "Ruines",
    "hi": "खंडहर",
    "pa": "ਖੰਡਰ",
    "pt-BR": "Ruínas"
  },
  "science": {
    "bg": "Наука",
    "de": "Wissenschaft",
    "en": "Science",
    "es": "Ciencia",
    "fr": "Science",
    "hi": "विज्ञान",
    "pa": "ਵਿਗਿਆਨ",
    "pt-BR": "Ciência"
  },
  "shoes": {
    "bg": "Обувки",
    "de": "Schuhe",
    "en": "Shoes",
    "es": "Zapatos",
    "fr": "Chaussures",
    "hi": "जूते",
    "pa": "ਜੁੱਤੀਆਂ",
    "pt-BR": "Sapatos"
  },
  "shop": {
    "bg": "Магазин",
    "de": "Laden",
    "en": "Shop",
    "es": "Tienda",
    "fr": "Boutique",
    "hi": "दुकान",
    "pa": "ਦੁਕਾਨ",
    "pt-BR": "Loja"
  },
  "skeleton": {
    "bg": "Скелет",
    "de": "Skelett",
    "en": "Skeleton",
    "es": "Esqueleto",
    "fr": "Squelette",
    "hi": "कंकाल",
    "pa": "ਪਿੰਜਰ",
    "pt-BR": "Esqueleto"
  },
  "skyscraper": {
    "bg": "Небостъргач",
    "de": "Wolkenkratzer",
    "en": "Skyscraper",
    "es": "Rascacielos",
    "fr": "Gratte-ciel",
    "hi": "गगनचुंबी इमारत",
    "pa": "ਗਗਨਚੁੰਬੀ ਇਮਾਰਤ",
    "pt-BR": "Arranha-céu"
  },
  "smartphone": {
    "bg": "Смартфон",
    "de": "Smartphone",
    "en": "Smartphone",
    "es": "Teléfono inteligente",
    "fr": "Smartphone",
    "hi": "स्मार्टफ़ोन",
    "pa": "ਸਮਾਰਟਫ਼ੋਨ",
    "pt-BR": "Smartphone"
  },
  "snowman": {
    "bg": "Снежен човек",
    "de": "Schneemann",
    "en": "Snowman",
    "es": "Muñeco de nieve",
    "fr": "Bonhomme de neige",
    "hi": "हिममानव",
    "pa": "ਬਰਫ਼ ਦਾ ਆਦਮੀ",
    "pt-BR": "Boneco de neve"
  },
  "soccer": {
    "bg": "Футбол",
    "de": "Fußball",
    "en": "Soccer",
    "es": "Fútbol",
    "fr": "Football",
    "hi": "फ़ुटबॉल",
    "pa": "ਫ਼ੁੱਟਬਾਲ",
    "pt-BR": "Futebol"
  },
  "summer": {
    "bg": "Лято",
    "de": "Sommer",
    "en": "Summer",
    "es": "Verano",
    "fr": "Été",
    "hi": "गर्मी",
    "pa": "ਗਰਮੀਆਂ",
    "pt-BR": "Verão"
  },
  "tank": {
    "bg": "Танк",
    "de": "Panzer",
    "en": "Tank",
    "es": "Tanque",
    "fr": "Char d’assaut",
    "hi": "टैंक",
    "pa": "ਟੈਂਕ",
    "pt-BR": "Tanque"
  },
  "train": {
    "bg": "Влак",
    "de": "Zug",
    "en": "Train",
    "es": "Tren",
    "fr": "Train",
    "hi": "ट्रेन",
    "pa": "ਰੇਲਗੱਡੀ",
    "pt-BR": "Trem"
  },
  "upside_down": {
    "bg": "С главата надолу",
    "de": "Kopfüber",
    "en": "Upside Down",
    "es": "Boca abajo",
    "fr": "À l’envers",
    "hi": "उल्टा",
    "pa": "ਉਲਟਾ-ਪੁਲਟਾ",
    "pt-BR": "De cabeça para baixo"
  },
  "volcano": {
    "bg": "Вулкан",
    "de": "Vulkan",
    "en": "Volcano",
    "es": "Volcán",
    "fr": "Volcan",
    "hi": "ज्वालामुखी",
    "pa": "ਜਵਾਲਾਮੁਖੀ",
    "pt-BR": "Vulcão"
  },
  "winter": {
    "bg": "Зима",
    "de": "Winter",
    "en": "Winter",
    "es": "Invierno",
    "fr": "Hiver",
    "hi": "सर्दी",
    "pa": "ਸਰਦੀਆਂ",
    "pt-BR": "Inverno"
  },
  "wizard": {
    "bg": "Магьосник",
    "de": "Zauberer",
    "en": "Wizard",
    "es": "Mago",
    "fr": "Sorcier",
    "hi": "जादूगर",
    "pa": "ਜਾਦੂਗਰ",
    "pt-BR": "Mago"
  }
};
